name: CI Pipeline

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest

    env:
      DOTNET_ENVIRONMENT: Test
      SKIP_ADMIN_CHECK: true

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET 8 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Cache NuGet Packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: nuget-${{ runner.os }}-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          nuget-${{ runner.os }}-

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Solution
      run: dotnet build --configuration Release --no-restore

    - name: Run Unit Tests
      run: dotnet test --configuration Release --no-build --verbosity normal --blame-hang-timeout 60 --diag:logfile.txt
      env:
        VSTEST_DISABLE_TESTHOST_SDK_RESOLVER: 1

    - name: Upload Test Logs (on Failure)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-logs
        path: logfile.txt

    - name: Publish Build Artifacts (optional)
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: ./StarCraftKeyManager/bin/Release/net8.0-windows/win-x64/
